# Site settings
title: SkeptiStats
email: ekt.batey@gmail.com
description: A website for exposing incorrect and dishonest use of statistics
baseurl: "/skeptistats" # the subpath of your site, e.g. /blog/
url: "http://bateyt.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  bateyt

# Build settings
markdown: kramdown

# Syntax highlighter
highlighter: rouge

# Set encoding
encoding: utf-8
